// Gatekeeper cropping data for M J Hunt & Son, Upper Assendon Farm
// Source: Gatekeeper Cropping Summary printed 06 May 2026
// Seasons: 2022–2027 harvest years
// "Corn Gromwell-Winter" in Gatekeeper = Wildfarmed winter wheat (Corn Gromwell conservation scheme)

import type { Field } from './types';
import type { FieldCropPlan } from './types';

// ── Field list with proper names ──────────────────────────────────────────────
// status: "In crop" = arable, "Grass" = permanent/temporary grass, "Cover crop" = ley in rotation
// All areas in ha from Gatekeeper
export const GATEKEEPER_FIELDS: Field[] = [
  { name: '20 acres',          area: 8.30,  status: 'In crop', crop: 'Winter wheat', notes: 'Wildfarmed – Corn Gromwell', parcel: 'GK-20acres' },
  { name: 'Assendon',          area: 10.50, status: 'Cover crop', crop: '', notes: 'Temporary ley – returning to wheat 26/27', parcel: 'GK-Assendon' },
  { name: 'Assendon small',    area: 6.00,  status: 'Cover crop', crop: '', notes: 'Temporary ley – returning to wheat 26/27', parcel: 'GK-AssendonSmall' },
  { name: 'Behind Keepers',    area: 9.49,  status: 'Cover crop', crop: '', notes: 'New ley 2026 – going to grass 26/27', parcel: 'GK-BehindKeepers' },
  { name: 'Behind Village',    area: 6.26,  status: 'Grass',      crop: '', notes: '', parcel: 'GK-BehindVillage' },
  { name: 'Big oak',           area: 6.01,  status: 'Cover crop', crop: '', notes: 'New ley 2026 – going to grass 26/27', parcel: 'GK-BigOak' },
  { name: 'Bix Manor',         area: 18.00, status: 'Grass',      crop: '', notes: 'Temporary ley – permanent grass 26/27', parcel: 'GK-BixManor' },
  { name: 'Black Dean & Pages',area: 9.00,  status: 'In crop',    crop: 'Winter wheat', notes: 'Skyfall · Bix Hall FBT', parcel: 'GK-BlackDean' },
  { name: 'Borderleys',        area: 10.50, status: 'In crop',    crop: 'Winter wheat', notes: '', parcel: 'GK-Borderleys' },
  { name: 'Church',            area: 7.00,  status: 'In crop',    crop: 'Winter wheat', notes: 'Skyfall · Bix Hall FBT', parcel: 'GK-Church' },
  { name: 'Fawley Bottom',     area: 16.00, status: 'In crop',    crop: 'Winter wheat', notes: 'Wildfarmed – Corn Gromwell', parcel: 'GK-FawleyBottom' },
  { name: 'Finger Wood',       area: 4.50,  status: 'Grass',      crop: '', notes: 'Temporary ley – going to grass 26/27', parcel: 'GK-FingerWood' },
  { name: 'Fir field',         area: 10.50, status: 'In crop',    crop: 'Spring wheat', notes: '', parcel: 'GK-FirField' },
  { name: 'Freedom',           area: 7.57,  status: 'In crop',    crop: 'Winter wheat', notes: 'Skyfall · Bix Hall FBT', parcel: 'GK-Freedom' },
  { name: 'Grange',            area: 38.00, status: 'In crop',    crop: 'Winter wheat', notes: 'Ultimatum', parcel: 'GK-Grange' },
  { name: 'Hangins Hill',      area: 12.50, status: 'In crop',    crop: 'Winter wheat', notes: 'Wildfarmed – Corn Gromwell', parcel: 'GK-HanginsHill' },
  { name: 'Herberts',          area: 4.00,  status: 'Grass',      crop: '', notes: 'Temporary ley – going to grass 26/27', parcel: 'GK-Herberts' },
  { name: 'Hoggetts',          area: 8.00,  status: 'Grass',      crop: '', notes: 'Temporary ley – going to grass 26/27', parcel: 'GK-Hoggetts' },
  { name: 'Holy Hill',         area: 4.00,  status: 'Grass',      crop: '', notes: 'Temporary ley – going to grass 26/27', parcel: 'GK-HolyHill' },
  { name: 'Launder',           area: 22.00, status: 'Grass',      crop: '', notes: 'Permanent grass', parcel: 'GK-Launder' },
  { name: 'Lewknor',           area: 40.00, status: 'In crop',    crop: 'Spring wheat', notes: '', parcel: 'GK-Lewknor' },
  { name: 'Lodge big',         area: 15.00, status: 'In crop',    crop: 'Spring wheat', notes: '', parcel: 'GK-LodgeBig' },
  { name: 'Lodge farm field',  area: 9.00,  status: 'In crop',    crop: 'Spring wheat', notes: '', parcel: 'GK-LodgeFarm' },
  { name: 'Lower Wanscome',    area: 7.00,  status: 'Grass',      crop: '', notes: 'Temporary ley – going to grass 26/27', parcel: 'GK-LowerWanscome' },
  { name: 'Naiboss',           area: 11.50, status: 'In crop',    crop: 'Winter wheat', notes: '', parcel: 'GK-Naiboss' },
  { name: 'Paradise',          area: 10.50, status: 'In crop',    crop: 'Winter wheat', notes: 'Wildfarmed – Corn Gromwell', parcel: 'GK-Paradise' },
  { name: 'Rowdow',            area: 8.99,  status: 'In crop',    crop: 'Winter barley', notes: '', parcel: 'GK-Rowdow' },
  { name: 'Rowley Meadow',     area: 4.50,  status: 'Grass',      crop: '', notes: 'Temporary ley – going to grass 26/27', parcel: 'GK-RowleyMeadow' },
  { name: 'Sale Field',        area: 6.80,  status: 'In crop',    crop: 'Winter wheat', notes: 'Skyfall', parcel: 'GK-SaleField' },
  { name: 'Scotts',            area: 5.50,  status: 'Grass',      crop: '', notes: 'Temporary ley – going to grass 26/27', parcel: 'GK-Scotts' },
  { name: 'Shenley',           area: 15.00, status: 'Grass',      crop: '', notes: 'Temporary ley – staying as ley 26/27', parcel: 'GK-Shenley' },
  { name: 'Silo Field',        area: 11.58, status: 'In crop',    crop: 'Winter wheat', notes: 'Wildfarmed – Corn Gromwell', parcel: 'GK-SiloField' },
  { name: 'Soundees',          area: 20.00, status: 'In crop',    crop: 'Winter wheat', notes: 'Skyfall', parcel: 'GK-Soundees' },
  { name: 'Spring pit',        area: 6.50,  status: 'In crop',    crop: 'Spring wheat', notes: '', parcel: 'GK-SpringPit' },
  { name: 'Steins Park',       area: 13.30, status: 'In crop',    crop: 'Winter wheat', notes: 'Wildfarmed – Corn Gromwell', parcel: 'GK-SteinsPark' },
  { name: 'Stockings',         area: 11.00, status: 'Grass',      crop: '', notes: 'Permanent grass', parcel: 'GK-Stockings' },
  { name: 'Stonor Road',       area: 5.20,  status: 'Grass',      crop: '', notes: 'Temporary ley – going to grass 26/27', parcel: 'GK-StonorRoad' },
  { name: 'The bank',          area: 10.00, status: 'In crop',    crop: 'Winter wheat', notes: 'Wildfarmed – Corn Gromwell', parcel: 'GK-TheBank' },
  { name: 'Top east',          area: 4.61,  status: 'In crop',    crop: 'Winter wheat', notes: 'Skyfall · Bix Hall FBT', parcel: 'GK-TopEast' },
  { name: 'Top Field',         area: 15.00, status: 'In crop',    crop: 'Winter wheat', notes: '', parcel: 'GK-TopField' },
  { name: 'Top Top East',      area: 3.10,  status: 'In crop',    crop: 'Winter wheat', notes: 'Skyfall', parcel: 'GK-TopTopEast' },
  { name: 'Upper Wanscome',    area: 5.28,  status: 'Grass',      crop: '', notes: 'Temporary ley – going to grass 26/27', parcel: 'GK-UpperWanscome' },
  { name: 'West field',        area: 5.20,  status: 'In crop',    crop: 'Spring wheat', notes: '', parcel: 'GK-WestField' },
  { name: 'Yew tree hill',     area: 9.00,  status: 'In crop',    crop: 'Spring wheat', notes: '', parcel: 'GK-YewTreeHill' },
];

// ── 25/26 season plan (2026 harvest – crops currently in the ground) ──────────
// Previous crops taken from 2025 column in Gatekeeper
export const GK_PLAN_2526: FieldCropPlan[] = [
  { fieldParcel: 'GK-20acres',     fieldName: '20 acres',          areaHa: 8.30,  plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-BlackDean',   fieldName: 'Black Dean & Pages', areaHa: 9.00,  plannedCrop: 'Winter wheat', variety: 'Skyfall',       contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Temporary grass', notes: 'Bix Hall FBT' },
  { fieldParcel: 'GK-Borderleys',  fieldName: 'Borderleys',         areaHa: 10.50, plannedCrop: 'Winter wheat', variety: '',              contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Spring beans' },
  { fieldParcel: 'GK-Church',      fieldName: 'Church',             areaHa: 7.00,  plannedCrop: 'Winter wheat', variety: 'Skyfall',       contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Temporary grass', notes: 'Bix Hall FBT' },
  { fieldParcel: 'GK-FawleyBottom',fieldName: 'Fawley Bottom',      areaHa: 16.00, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring wheat' },
  { fieldParcel: 'GK-FirField',    fieldName: 'Fir field',          areaHa: 10.50, plannedCrop: 'Spring wheat', variety: '',              contractType: 'Feed',       targetYieldTha: 6.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Freedom',     fieldName: 'Freedom',            areaHa: 7.57,  plannedCrop: 'Winter wheat', variety: 'Skyfall',       contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Temporary grass', notes: 'Bix Hall FBT' },
  { fieldParcel: 'GK-Grange',      fieldName: 'Grange',             areaHa: 38.00, plannedCrop: 'Winter wheat', variety: 'Ultimatum',     contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-HanginsHill', fieldName: 'Hangins Hill',       areaHa: 12.50, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Lewknor',     fieldName: 'Lewknor',            areaHa: 40.00, plannedCrop: 'Spring wheat', variety: '',              contractType: 'Feed',       targetYieldTha: 6.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-LodgeBig',    fieldName: 'Lodge big',          areaHa: 15.00, plannedCrop: 'Spring wheat', variety: '',              contractType: 'Feed',       targetYieldTha: 6.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-LodgeFarm',   fieldName: 'Lodge farm field',   areaHa: 9.00,  plannedCrop: 'Spring wheat', variety: '',              contractType: 'Feed',       targetYieldTha: 6.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Naiboss',     fieldName: 'Naiboss',            areaHa: 11.50, plannedCrop: 'Winter wheat', variety: '',              contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Spring beans' },
  { fieldParcel: 'GK-Paradise',    fieldName: 'Paradise',           areaHa: 10.50, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Rowdow',      fieldName: 'Rowdow',             areaHa: 8.99,  plannedCrop: 'Winter barley', variety: '',             contractType: 'Feed',       targetYieldTha: 7.0, estimatedPricePerT: 165, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-SaleField',   fieldName: 'Sale Field',         areaHa: 6.80,  plannedCrop: 'Winter wheat', variety: 'Skyfall',       contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring beans' },
  { fieldParcel: 'GK-SiloField',   fieldName: 'Silo Field',         areaHa: 11.58, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Soundees',    fieldName: 'Soundees',           areaHa: 20.00, plannedCrop: 'Winter wheat', variety: 'Skyfall',       contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Temporary grass' },
  { fieldParcel: 'GK-SpringPit',   fieldName: 'Spring pit',         areaHa: 6.50,  plannedCrop: 'Spring wheat', variety: '',              contractType: 'Feed',       targetYieldTha: 6.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-SteinsPark',  fieldName: 'Steins Park',        areaHa: 13.30, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring wheat' },
  { fieldParcel: 'GK-TheBank',     fieldName: 'The bank',           areaHa: 10.00, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring wheat' },
  { fieldParcel: 'GK-TopEast',     fieldName: 'Top east',           areaHa: 4.61,  plannedCrop: 'Winter wheat', variety: 'Skyfall',       contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring beans', notes: 'Bix Hall FBT' },
  { fieldParcel: 'GK-TopField',    fieldName: 'Top Field',          areaHa: 15.00, plannedCrop: 'Winter wheat', variety: '',              contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Spring beans' },
  { fieldParcel: 'GK-TopTopEast',  fieldName: 'Top Top East',       areaHa: 3.10,  plannedCrop: 'Winter wheat', variety: 'Skyfall',       contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring beans' },
  { fieldParcel: 'GK-WestField',   fieldName: 'West field',         areaHa: 5.20,  plannedCrop: 'Spring wheat', variety: '',              contractType: 'Feed',       targetYieldTha: 6.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-YewTreeHill', fieldName: 'Yew tree hill',      areaHa: 9.00,  plannedCrop: 'Spring wheat', variety: '',              contractType: 'Feed',       targetYieldTha: 6.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
];

// ── 26/27 season plan (2027 harvest – planned crops, drilled autumn 2026) ─────
// Corn Gromwell-Winter in Gatekeeper = Wildfarmed winter wheat
// Previous crop = 2026 harvest crop (25/26 season)
export const GK_PLAN_2627: FieldCropPlan[] = [
  { fieldParcel: 'GK-20acres',     fieldName: '20 acres',          areaHa: 8.30,  plannedCrop: 'Winter wheat', variety: '', contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Assendon',    fieldName: 'Assendon',          areaHa: 10.50, plannedCrop: 'Winter wheat', variety: '', contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Grass ley' },
  { fieldParcel: 'GK-AssendonSmall',fieldName: 'Assendon small',   areaHa: 6.00,  plannedCrop: 'Winter wheat', variety: '', contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Grass ley' },
  { fieldParcel: 'GK-BlackDean',   fieldName: 'Black Dean & Pages', areaHa: 9.00, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat', notes: 'Bix Hall FBT' },
  { fieldParcel: 'GK-Borderleys',  fieldName: 'Borderleys',         areaHa: 10.50, plannedCrop: 'Spring wheat', variety: '', contractType: 'Feed',      targetYieldTha: 6.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Church',      fieldName: 'Church',             areaHa: 7.00,  plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat', notes: 'Bix Hall FBT' },
  { fieldParcel: 'GK-FawleyBottom',fieldName: 'Fawley Bottom',      areaHa: 16.00, plannedCrop: 'Winter wheat', variety: '', contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Freedom',     fieldName: 'Freedom',            areaHa: 7.57,  plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat', notes: 'Bix Hall FBT' },
  { fieldParcel: 'GK-Grange',      fieldName: 'Grange',             areaHa: 38.00, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-HanginsHill', fieldName: 'Hangins Hill',       areaHa: 12.50, plannedCrop: 'Winter wheat', variety: '', contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Lewknor',     fieldName: 'Lewknor',            areaHa: 40.00, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring wheat' },
  { fieldParcel: 'GK-LodgeBig',    fieldName: 'Lodge big',          areaHa: 15.00, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring wheat' },
  { fieldParcel: 'GK-LodgeFarm',   fieldName: 'Lodge farm field',   areaHa: 9.00,  plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring wheat' },
  { fieldParcel: 'GK-Naiboss',     fieldName: 'Naiboss',            areaHa: 11.50, plannedCrop: 'Spring wheat', variety: '', contractType: 'Feed',       targetYieldTha: 6.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Paradise',    fieldName: 'Paradise',           areaHa: 10.50, plannedCrop: 'Winter wheat', variety: '', contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Rowdow',      fieldName: 'Rowdow',             areaHa: 8.99,  plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter barley' },
  { fieldParcel: 'GK-SaleField',   fieldName: 'Sale Field',         areaHa: 6.80,  plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-SiloField',   fieldName: 'Silo Field',         areaHa: 11.58, plannedCrop: 'Winter wheat', variety: '', contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-Soundees',    fieldName: 'Soundees',           areaHa: 20.00, plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-SteinsPark',  fieldName: 'Steins Park',        areaHa: 13.30, plannedCrop: 'Winter wheat', variety: '', contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-TheBank',     fieldName: 'The bank',           areaHa: 10.00, plannedCrop: 'Winter wheat', variety: '', contractType: 'Feed',       targetYieldTha: 8.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-TopEast',     fieldName: 'Top east',           areaHa: 4.61,  plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat', notes: 'Bix Hall FBT' },
  { fieldParcel: 'GK-TopField',    fieldName: 'Top Field',          areaHa: 15.00, plannedCrop: 'Spring wheat', variety: '', contractType: 'Feed',       targetYieldTha: 6.0, estimatedPricePerT: 192, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-TopTopEast',  fieldName: 'Top Top East',       areaHa: 3.10,  plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Winter wheat' },
  { fieldParcel: 'GK-WestField',   fieldName: 'West field',         areaHa: 5.20,  plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring wheat' },
  { fieldParcel: 'GK-YewTreeHill', fieldName: 'Yew tree hill',      areaHa: 9.00,  plannedCrop: 'Winter wheat', variety: 'Corn Gromwell', contractType: 'Wildfarmed', targetYieldTha: 7.5, estimatedPricePerT: 240, previousCrop: 'Spring wheat' },
];

// ── Rotation history (for context / Farm Bible) ───────────────────────────────
// Maps field name → { 2022, 2023, 2024, 2025, 2026, 2027 }
export const GK_ROTATION_HISTORY: Record<string, Record<string, string>> = {
  '20 acres':           { '2022': 'Skyfall',      '2023': 'Spring beans', '2024': 'Skyfall',       '2025': 'Extase',       '2026': 'Winter wheat (CG)', '2027': 'Winter wheat' },
  'Assendon':           { '2022': 'Skyfall',      '2023': 'Skyfall',      '2024': 'Skyfall',       '2025': 'Grass',        '2026': 'Grass',             '2027': 'Winter wheat' },
  'Assendon small':     { '2022': 'Skyfall',      '2023': 'Skyfall',      '2024': 'Skyfall',       '2025': 'Grass',        '2026': 'Grass',             '2027': 'Winter wheat' },
  'Behind Keepers':     { '2022': 'Skyfall',      '2023': 'Ultimatum',    '2024': 'New ley',       '2025': 'Spring barley','2026': 'New ley',           '2027': 'Grass' },
  'Behind Village':     { '2022': 'Spring barley','2023': 'Spring barley','2024': 'Spring barley', '2025': 'Grass',        '2026': 'Grass',             '2027': 'Spring barley' },
  'Big oak':            { '2022': 'Extase',       '2023': 'Grass',        '2024': 'Grass',         '2025': 'Ultimatum',    '2026': 'New ley',           '2027': 'Grass' },
  'Bix Manor':          { '2022': 'Extase',       '2023': 'Skyfall',      '2024': 'Temp grass',    '2025': 'Temp grass',   '2026': 'Temp grass',        '2027': 'Grass' },
  'Black Dean & Pages': { '2022': 'Spring wheat', '2023': 'Spring wheat', '2024': 'Temp grass',    '2025': 'Temp grass',   '2026': 'Skyfall',           '2027': 'Winter wheat (CG)' },
  'Borderleys':         { '2022': 'Extase',       '2023': 'Extase',       '2024': 'Extase',        '2025': 'Spring beans', '2026': 'Winter wheat',      '2027': 'Spring wheat' },
  'Church':             { '2022': 'Spring wheat', '2023': 'Spring wheat', '2024': 'Temp grass',    '2025': 'Temp grass',   '2026': 'Skyfall',           '2027': 'Winter wheat (CG)' },
  'Fawley Bottom':      { '2022': 'Skyfall',      '2023': 'Spring wheat', '2024': 'Skyfall',       '2025': 'Spring wheat', '2026': 'Winter wheat (CG)', '2027': 'Winter wheat' },
  'Finger Wood':        { '2022': 'KWS Zyatt',    '2023': 'Winter barley','2024': 'Winter barley', '2025': 'Skyfall',      '2026': 'Temp grass',        '2027': 'Grass' },
  'Fir field':          { '2022': 'Extase',       '2023': 'Skyfall',      '2024': 'Spring wheat',  '2025': 'Ultimatum',    '2026': 'Spring wheat',      '2027': 'Grass' },
  'Freedom':            { '2022': 'Spring wheat', '2023': 'Spring wheat', '2024': 'Temp grass',    '2025': 'Temp grass',   '2026': 'Skyfall',           '2027': 'Winter wheat (CG)' },
  'Grange':             { '2022': 'Winter barley','2023': 'Winter barley','2024': 'Winter barley', '2025': 'Ultimatum',    '2026': 'Ultimatum',         '2027': 'Winter wheat (CG)' },
  'Hangins Hill':       { '2022': 'Skyfall',      '2023': 'Spring beans', '2024': 'Skyfall',       '2025': 'Extase',       '2026': 'Winter wheat (CG)', '2027': 'Winter wheat' },
  'Herberts':           { '2022': 'KWS Zyatt',    '2023': 'Winter barley','2024': 'Winter barley', '2025': 'Skyfall',      '2026': 'Temp grass',        '2027': 'Grass' },
  'Hoggetts':           { '2022': 'KWS Zyatt',    '2023': 'Winter barley','2024': 'Winter barley', '2025': 'Skyfall',      '2026': 'Temp grass',        '2027': 'Grass' },
  'Holy Hill':          { '2022': 'KWS Zyatt',    '2023': 'Skyfall',      '2024': 'Skyfall',       '2025': 'Skyfall',      '2026': 'Temp grass',        '2027': 'Grass' },
  'Launder':            { '2022': 'Grass',        '2023': 'Grass',        '2024': 'Grass',         '2025': 'Grass',        '2026': 'Grass',             '2027': 'Grass' },
  'Lewknor':            { '2022': 'Winter wheat (CG)', '2023': 'Extase', '2024': 'Extase',         '2025': 'Extase',       '2026': 'Spring wheat',      '2027': 'Winter wheat (CG)' },
  'Lodge big':          { '2022': 'Spring wheat', '2023': 'Winter wheat (CG)', '2024': 'Ultimatum', '2025': 'Ultimatum',   '2026': 'Spring wheat',      '2027': 'Winter wheat (CG)' },
  'Lodge farm field':   { '2022': 'Spring wheat', '2023': 'Winter wheat (CG)', '2024': 'Ultimatum', '2025': 'Ultimatum',   '2026': 'Spring wheat',      '2027': 'Winter wheat (CG)' },
  'Lower Wanscome':     { '2022': 'KWS Zyatt',    '2023': 'Skyfall',      '2024': 'Skyfall',       '2025': 'Skyfall',      '2026': 'Temp grass',        '2027': 'Grass' },
  'Naiboss':            { '2022': 'Extase',       '2023': 'Dawsum',       '2024': 'Extase',        '2025': 'Spring beans', '2026': 'Winter wheat',      '2027': 'Spring wheat' },
  'Paradise':           { '2022': 'Skyfall',      '2023': 'Skyfall',      '2024': 'Skyfall',       '2025': 'Extase',       '2026': 'Winter wheat (CG)', '2027': 'Winter wheat' },
  'Rowdow':             { '2022': 'KWS Zyatt',    '2023': 'Grass',        '2024': 'Grass',         '2025': 'Ultimatum',    '2026': 'Winter barley',     '2027': 'Winter wheat (CG)' },
  'Rowley Meadow':      { '2022': 'Spring barley','2023': 'Spring wheat', '2024': 'Skyfall',       '2025': 'Skyfall',      '2026': 'Temp grass',        '2027': 'Grass' },
  'Sale Field':         { '2022': 'Spring wheat', '2023': 'Spring wheat', '2024': 'Skyfall',       '2025': 'Spring beans', '2026': 'Skyfall',           '2027': 'Winter wheat (CG)' },
  'Scotts':             { '2022': 'KWS Zyatt',    '2023': 'Skyfall',      '2024': 'Skyfall',       '2025': 'Skyfall',      '2026': 'Temp grass',        '2027': 'Grass' },
  'Shenley':            { '2022': 'Skyfall',      '2023': 'Skyfall',      '2024': 'Temp grass',    '2025': 'Temp grass',   '2026': 'Temp grass',        '2027': 'Temp grass' },
  'Silo Field':         { '2022': 'Temp grass',   '2023': 'Winter wheat', '2024': 'Skyfall',       '2025': 'Extase',       '2026': 'Winter wheat (CG)', '2027': 'Winter wheat' },
  'Soundees':           { '2022': 'KWS Zyatt',    '2023': 'Skyfall',      '2024': 'Temp grass',    '2025': 'Temp grass',   '2026': 'Skyfall',           '2027': 'Winter wheat (CG)' },
  'Spring pit':         { '2022': 'Spring wheat', '2023': 'Skyfall',      '2024': 'Spring wheat',  '2025': 'Ultimatum',    '2026': 'Spring wheat',      '2027': 'Grass' },
  'Steins Park':        { '2022': 'Skyfall',      '2023': 'Skyfall',      '2024': 'Spring wheat',  '2025': 'Spring wheat', '2026': 'Winter wheat (CG)', '2027': 'Winter wheat' },
  'Stockings':          { '2022': 'Grass',        '2023': 'Grass',        '2024': 'Grass',         '2025': 'Grass',        '2026': 'Grass',             '2027': 'Grass' },
  'Stonor Road':        { '2022': 'KWS Zyatt',    '2023': 'Winter barley','2024': 'Winter barley', '2025': 'Skyfall',      '2026': 'Temp grass',        '2027': 'Grass' },
  'The bank':           { '2022': 'Skyfall',      '2023': 'Spring wheat', '2024': 'Spring wheat',  '2025': 'Spring wheat', '2026': 'Winter wheat (CG)', '2027': 'Winter wheat' },
  'Top east':           { '2022': 'Spring wheat', '2023': 'Spring wheat', '2024': 'Skyfall',       '2025': 'Spring beans', '2026': 'Skyfall',           '2027': 'Winter wheat (CG)' },
  'Top Field':          { '2022': 'Extase',       '2023': 'Extase',       '2024': 'Extase',        '2025': 'Spring beans', '2026': 'Winter wheat',      '2027': 'Spring wheat' },
  'Top Top East':       { '2022': 'Spring wheat', '2023': 'Spring wheat', '2024': 'Skyfall',       '2025': 'Spring beans', '2026': 'Skyfall',           '2027': 'Winter wheat (CG)' },
  'Upper Wanscome':     { '2022': 'KWS Zyatt',    '2023': 'Skyfall',      '2024': 'Temp grass',    '2025': 'Temp grass',   '2026': 'Temp grass',        '2027': 'Grass' },
  'West field':         { '2022': 'Spring wheat', '2023': 'Winter wheat (CG)', '2024': 'Ultimatum', '2025': 'Ultimatum',   '2026': 'Spring wheat',      '2027': 'Winter wheat (CG)' },
  'Yew tree hill':      { '2022': 'Spring wheat', '2023': 'Winter wheat (CG)', '2024': 'Ultimatum', '2025': 'Ultimatum',   '2026': 'Spring wheat',      '2027': 'Winter wheat (CG)' },
};
